### ISSUE TITLE
有些书插件显示无，但是微信读书里面其实有，这种情况如何快捷反馈

### ISSUE THREAD

**Issue by sysuyep** [Sorosliu1029/weReaDou#2]
比如这本书 https://book.douban.com/subject/35051997/

**Comment by Sorosliu1029** [comment]
这个插件会同时比较书名和作者信息，只有比较结果相差不大时，才会认为是匹配的。

截图分别是豆瓣和微信读书上对应的《本质思考》图书信息

豆瓣：
![image](https://user-images.githubusercontent.com/8862646/105124091-56488980-5b14-11eb-96d9-6586e7ee0031.png)

微信读书：
![image](https://user-images.githubusercontent.com/8862646/105124100-5c3e6a80-5b14-11eb-8bfc-bf0fa2921f45.png)

两者书名一致，但作者名上相差较大（注意到豆瓣上的条目为「 [日]米泽创一 著 时代华语 出品」），所以被插件识别为不相关图书，而被过滤掉了。

可行的方法是去豆瓣修改该条目：
![image](https://user-images.githubusercontent.com/8862646/105124275-cb1bc380-5b14-11eb-857f-62b9ed44a239.png)
